# -*- coding: utf-8 -*-
"""dl6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UcLqNP0vjDYHjuWkqd3J0y3WT9bsZzC-
"""

!pip install transformers datasets torch scikit-learn


import torch
from datasets import load_dataset
from transformers import BertTokenizer, BertForSequenceClassification
from transformers import Trainer, TrainingArguments

dataset = load_dataset("emotion")

train_dataset = dataset["train"].shuffle(seed=42).select(range(200))
test_dataset = dataset["test"].shuffle(seed=42).select(range(50))

labels = ["sadness","joy","love","anger","fear","surprise"]

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

def tokenize(example):
    return tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=64
    )

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

train_dataset.set_format(type="torch", columns=["input_ids","attention_mask","label"])
test_dataset.set_format(type="torch", columns=["input_ids","attention_mask","label"])

model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=6
)

training_args = TrainingArguments(
    output_dir="./results",
    max_steps=15,
    per_device_train_batch_size=8,
    logging_steps=1
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

trainer.train()
def predict_emotion(text):

    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)

    outputs = model(**inputs)

    probs = torch.nn.functional.softmax(outputs.logits, dim=1)

    prediction = torch.argmax(probs).item()

    return labels[prediction]

print("\nPredictions:\n")

print("Text: I am very happy today")
print("Emotion:", predict_emotion("I am very happy today"))

print("\nText: I feel very sad and lonely")
print("Emotion:", predict_emotion("I feel very sad and lonely"))